# Generated by Django 4.2.7 on 2024-04-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_image_dessert_dessert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='dessert_image',
            field=models.ImageField(blank=True, null=True, upload_to='desert_image'),
        ),
    ]
