# Generated by Django 4.2.7 on 2024-03-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='optional',
            field=models.CharField(choices=[('DB', 'DBMS'), ('net', 'Networkig')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
