# Generated by Django 4.2.7 on 2024-04-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dessert_dessert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='dessert_image',
            field=models.ImageField(blank=True, default=' ', upload_to='desert_image'),
            preserve_default=False,
        ),
    ]
