# Generated by Django 4.2.7 on 2024-03-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_optional'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
