# Generated by Django 4.2.7 on 2024-03-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=20)),
                ('optional', models.CharField(choices=[('DB', 'DBMS'), ('NET', 'networking')], max_length=50)),
            ],
        ),
    ]
